// src/script/component/sample3.vue
<template lang='pug'>
  section.container
    h2 Action Sample
    p Current is {{count}}.
    button(v-on:click="increment") increment
    button(v-on:click="decrement") decrement
</template>

<script>
  export default {
    data: () => ({
      count: 0,
    }),
    methods: {
      increment () {
        this.count += 1
      },
      decrement () {
        this.count -= 1
      },
    }
  }
</script>

<style scoped>
</style>

// src/script/components/sample3.jsx
import React, { useState, useEffect } from 'react';

export default () => {
  const [count, setCount] = useState(0);

  // Similar to componentDidMount and componentDidUpdate:
  useEffect(() => {
    if (count != 0 && count%3 == 0) window.alert(`Your count is ${count}!! 🎉`);
  });

  return (
    <section className='container'>
      <h2>Action Sample</h2>
      <p>Current is { count }.</p>
      <button onClick={() => setCount(count - 1)}>-</button>
      <button onClick={() => setCount(count + 1)}>+</button>
    </section>
  );
}
