// src/script/component/sample2.vue
<template lang='pug'>
  section.template-container
    div
      h2 Binding Sample
      p Hello! {{name}}!
      input(type="text", v-model="name", placeholder="enter a name here")
</template>

<script>
  export default {
    data: () => ({
      name: '',
    })
  }
</script>

<style scoped>
</style>

// src/script/components/sample2.jsx
import React, { useState } from 'react';

export default () => {
  const [name, setName] = useState('');

  return (
    <section className='container'>
      <h2>Binding Sample</h2>
      <p>Hello! { name }!!</p>
      <input type='text' placeholder='enter a name here' onChange={e => setName(e.target.value)} value={name} />
    </section>
  );
};
